### ISSUE TITLE
win10 vs2017 cmake_build.py failed.

### ISSUE THREAD

**Issue by marshal-it** [samdauwe/BabylonCpp#80] opened 2020-05-31 06:28 UTC
![image](https://user-images.githubusercontent.com/3109971/83345946-eac66780-a34a-11ea-920c-412335644fc4.png)

**Comment by samdauwe** [comment] 2020-05-31 07:40
Hi,

Thanks for trying out this project!

On my side I cannot reproduce this error:
![cmake_build](https://user-images.githubusercontent.com/24841018/83346946-775c3000-a321-11ea-83d9-58099b4f8a2d.png)

The build seems to fail in the cmake step, but the real error is not revealed in the log.

Could you manually try running cmake as follows:

```console
cd D:\GitHub\BabylonCpp
mkdir build
cd build
cmake .. -G"Visual Studio 15 2017 Win64"
```
If this succeeds you should have a Visual Studio solution file in the _build_ directory that you can open in Visual Studio. Alternatively you can trigger the build from the command line as follows:

```console
cmake --build . --config Debug
```

Best regards,
Sam

**Comment by samdauwe** [comment] 2020-06-17 19:05
Hi,

I am closing this issue because it cannot be reproduced on my side or on AppVeyor CI.

Best regards,
Sam

**Closed by samdauwe** 2020-06-17 19:05 UTC
